apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  namespace: fcg
  labels:
    app: users-api
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=FCG_Users;User Id=sa;Password=FCG@Pass123!;TrustServerCertificate=True"
  Jwt__Chave: "FCG-Fase2-JWT-SharedKey-2026-FIAP!@#$%^&"
  RabbitMQ__Password: "guest"
